from src.BaseClassesForNM import Page, Style

# Define different styles if needed
default_style = Style(body_bg="#261192",
    text_color="#c5fcef",
    extra_css="""
        h1, h2, h3 { color: #66baab; margin-top: 1.5em; margin-bottom: 0.5em; }
        a { color: #4d8075; text-decoration: none; transition: color 0.2s; }
        a:hover, a:focus { color: #66baab; text-decoration: underline; }
        .highlight, .card, .box {
            background: #c5fcef; color: #261192;
            border-radius: 10px; padding: 1em; margin-bottom: 1em;
            box-shadow: 0 2px 8px rgba(38,17,146,0.07);
        }
        button, .btn {
            background: #4d8075; color: #fff; border: none; border-radius: 4px;
            padding: 0.5em 1.5em; cursor: pointer; transition: background 0.2s;
        }
        button:hover, .btn:hover { background: #66baab; }
        footer {
            background: #261192; color: #4d8075; text-align: center; padding: 1em;
            font-size: 0.9em; margin-top: 2em; border-top: 1px solid #4d8075;
        }
    """)
about_style = Style(extra_css="h1 { text-transform: uppercase; }")
contact_style = Style(extra_css="h1 { text-transform: uppercase; }")

# Define pages
home_page = Page(
    title="Home",
    body="<p>Welcome to the homepage!</p>",
    links=[("About", "/about/"), ("Contact", "/contact/")],
    style=default_style,
    filename="index.html"
)

about_page = Page(
    title="About",
    body="<p>This site is generated by Python scripts. Enjoy browsing!</p>",
    links=[("Home", "/"), ("Contact", "/contact/")],
    style=about_style,
    filename="about/index.html"
)

contact_page = Page(
    title="Contact",
    body="<p>Email us at <a href='mailto:info@example.com'>info@example.com</a>.</p>",
    links=[("Home", "/"), ("About", "/about/")],
    style=contact_style,
    filename="contact/index.html"
)
