from src.BaseClassesForNM import Page, Style

# Define different styles if needed
default_style = Style(extra_css="h1 { text-transform: uppercase; }")
about_style = Style(extra_css="h1 { text-transform: uppercase; }")
contact_style = Style(extra_css="h1 { text-transform: uppercase; }")

# Define pages
home_page = Page(
    title="Home",
    body="<p>Welcome to the homepage!</p>",
    links=[("About", "about.html"), ("Contact", "contact.html")],
    style=default_style,
    filename="index.html"
)

about_page = Page(
    title="About",
    body="<p>This site is generated by Python scripts. Enjoy browsing!</p>",
    links=[("Home", "index.html"), ("Contact", "contact.html")],
    style=about_style,
    filename="about.html"
)

contact_page = Page(
    title="Contact",
    body="<p>Email us at <a href='mailto:info@example.com'>info@example.com</a>.</p>",
    links=[("Home", "index.html"), ("About", "about.html")],
    style=contact_style,
    filename="contact.html"
)
